apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jyz89z70a-nodejs-gitops
  description: This is GitOps manifest for jyz89z70a-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jyz89z70a-nodejs
    janus-idp.io/tekton: jyz89z70a-nodejs
    backstage.io/kubernetes-id: jyz89z70a-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jyz89z70a-nodejs
