apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jyz89z70a-nodejs
  janus-idp.io/tekton: jyz89z70a-nodejs
  backstage.io/kubernetes-id: jyz89z70a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jyz89z70a-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
