apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jyz89z70a-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jyz89z70a-nodejs 
  name: jyz89z70a-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jyz89z70a-nodejs 
